language: cpp

before_install:
        - sudo add-apt-repository -y ppa:boost-latest/ppa
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update;

install:
        - if [ "$CXX" == "clang++" ]; then .travis_scripts/clang.sh; fi
        - if [ "$CXX" == "g++"     ]; then .travis_scripts/gcc.sh; fi

before_script: 
        - sudo apt-get install -qq boost1.55
        - sudo apt-get install -qq libasio-dev1.10

script: 
        - mkdir build
        - cd build
        - cmake ..
        - make
