language: cpp

install:
        - if [ "$CXX" == "clang++" ]; then .travis_scripts/clang.sh; fi
        - if [ "$CXX" == "g++"     ]; then .travis_scripts/gcc.sh; fi

before_script: sudo apt-get install libasio-dev

script: 
        - mkdir build
        - cd build
        - cmake ..
        - make
